# Generated by Django 5.0.6 on 2024-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_employee_photo_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='photo', upload_to='employee_photos/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
